# CLOUD DATABASE CONFIGURATION
spring.datasource.url=${PROD_DB_URL}
spring.datasource.username=${PROD_DB_USERNAME}
spring.datasource.password=${PROD_DB_PASSWORD}

# It is usually safer to use 'validate' or 'update' in prod.
spring.jpa.hibernate.ddl-auto=update